src/main/java/it/gov/pagopa/payhub/activities/dto/CityDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ElaboratedInstallmentPrimaryOrganizationDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ElaboratedMultiBeneficiaryInstallmentDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/InstallmentPrimaryOrganizationDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/InstallmentsOperatorDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/MultiBeneficiaryInstallmentDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/NationDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/OrganizationDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/OrganizationInstallmentTypeDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/OrganizationTypeInstallmentDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ProvinceDTO.java
src/main/java/it/gov/pagopa/payhub/activities/dto/RegistryStatusDTO.java

feat: Traslated dto object

---

.github/workflows/codereview.yml
build.gradle.kts
src/main/java/it/gov/pagopa/payhub/activities/dto/NationDTO.java

chore: Add Code Review

---

build.gradle.kts
src/main/java/it/gov/pagopa/payhub/activities/dto/OrganizationDTO.java
src/test/java/it/gov/pagopa/payhub/activities/activity/AuthorizeOperatorOnDebtPositionTypeActivityTest.java

fix: Add field statusType to organizationDto

---

build.gradle.kts

chore: Fix Version

---

src/main/java/it/gov/pagopa/payhub/activities/dto/OrganizationDTO.java

fix: Remove field statusType from OrganizationDTO

---

src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/AuthorizeOperatorOnDebtPositionTypeActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/AuthorizeOperatorOnDebtPositionTypeActivityImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/AuthorizeOperatorOnDebtPositionTypeActivityTest.java

fix: Introducing @Lazy activities

---

.github/terraform/00_data.tf
.github/terraform/99_locals.tf

fix: Added SLACK_WEBHOOK_URL secret in github

---

src/main/java/it/gov/pagopa/payhub/activities/dao/IngestionFlowFileDao.java

fix: removed unused DAO method

---

src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/treasury/TreasuryOpiIngestionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/dto/IngestionFlowFileDTO.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/email/IngestionFlowFileEmailDestinationRetrieverService.java
src/main/java/it/gov/pagopa/payhub/activities/service/paymentsreporting/PaymentsReportingMapperService.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/SaveDebtPositionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/treasury/TreasuryOpiIngestionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/email/IngestionFlowFileEmailDestinationRetrieverServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/paymentsreporting/PaymentsReportingMapperServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/util/TestUtils.java
src/test/java/it/gov/pagopa/payhub/activities/utility/faker/IngestionFlowFileFaker.java

fix: aligning ingestion flow file model

---

src/main/java/it/gov/pagopa/payhub/activities/config/RestTemplateConfig.java
src/main/resources/config/application.yml

fix: Fix rest default timeout config

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/UpdateIngestionFlowStatusActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/UpdateIngestionFlowStatusActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/IngestionFlowFileService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/IngestionFlowFileServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/client/IngestionFlowFileClient.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/UpdateIngestionFlowStatusActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/aspect/NotRetryableActivityExceptionHandlerAspectTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/IngestionFlowFileServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/client/IngestionFlowFileClientTest.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/DebtPositionFaker.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/InstallmentFaker.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/PaymentOptionFaker.java

fix: Fix update IngestionFlowStatus activity

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/UpdateIngestionFlowStatusActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/UpdateIngestionFlowStatusActivityImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/UpdateIngestionFlowStatusActivityTest.java

fix: UpdateIngestionFlowStatusActivity error handling

---

src/main/java/it/gov/pagopa/payhub/activities/config/JsonConfig.java

fix: Fix datetime deserialization

---

src/main/java/it/gov/pagopa/payhub/activities/config/json/JsonConfig.java
src/main/java/it/gov/pagopa/payhub/activities/config/json/LocalDateTimeToOffsetDateTimeSerializer.java
src/main/java/it/gov/pagopa/payhub/activities/config/json/OffsetDateTimeToLocalDateTimeDeserializer.java
src/main/java/it/gov/pagopa/payhub/activities/service/ZipFileService.java
src/main/resources/config/application.yml
src/test/java/it/gov/pagopa/payhub/activities/config/json/LocalDateTimeToOffsetDateTimeSerializerTest.java
src/test/java/it/gov/pagopa/payhub/activities/config/json/OffsetDateTimeToLocalDateTimeDeserializerTest.java

fix: Fix LocalDateTime json serialization

---

src/main/java/it/gov/pagopa/payhub/activities/config/json/OffsetDateTimeToLocalDateTimeDeserializer.java
src/test/java/it/gov/pagopa/payhub/activities/config/json/OffsetDateTimeToLocalDateTimeDeserializerTest.java

fix: LocalDateTime json serialization when UTC

---

src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/IngestionFlowFileArchiverService.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/IngestionFlowFileArchiverServiceTest.java

fix: Archive op

---

src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/PaymentsReportingPagoPaService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/PaymentsReportingPagoPaServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/client/PaymentsReportingPagoPaClient.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/PaymentsReportingPagoPaServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/client/PaymentsReportingPagoPaClientTest.java

fix: Payments reporting fetch will ask for filename

---

src/main/java/it/gov/pagopa/payhub/activities/connector/debtposition/DebtPositionServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/util/DebtPositionUtilities.java

fix: Externalize debt position duedate extraction

---

src/main/java/it/gov/pagopa/payhub/activities/activity/classifications/IufClassificationActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/DebtPositionExpirationActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/FinalizeDebtPositionSyncStatusActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/aca/SynchronizeInstallmentAcaActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpd/SynchronizeInstallmentGpdActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpd/SynchronizeInstallmentGpdActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpdpreload/SynchronizeInstallmentGpdPreLoadActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpdpreload/SynchronizeInstallmentGpdPreLoadActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/GpdPreLoadService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/GpdPreLoadServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/GpdService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/GpdServiceImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpd/SynchronizeInstallmentGpdActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpdpreload/SynchronizeInstallmentGpdPreLoadActivityTest.java

feat: DebtPosition sync activities

---

src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpd/SynchronizeInstallmentGpdActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpd/SynchronizeInstallmentGpdActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/GpdService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/GpdServiceImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/gpd/SynchronizeInstallmentGpdActivityTest.java

fix: GPD activity should return iupd_pagopa

---

src/main/java/it/gov/pagopa/payhub/activities/config/EmailTemplatesConfiguration.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/email/IngestionFlowFileEmailTemplateResolverService.java
src/main/resources/config/mail-templates.properties
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/email/IngestionFlowFileEmailTemplateResolverServiceTest.java

feat: P4ADEV-2236 ingestionFlowFileType DP_INSTALLMENTS email templates

---

src/main/java/it/gov/pagopa/payhub/activities/mapper/ingestionflow/receipt/ReceiptMapper.java
src/test/java/it/gov/pagopa/payhub/activities/mapper/ingestionflow/receipt/ReceiptMapperTest.java
version

fix receipt mapper: subject may be null
fix receipt mapper: subject may be null
fix receipt mapper: subject may be null

fix: Fix receipt mapper: subject may be null

---

src/main/java/it/gov/pagopa/payhub/activities/util/DebtPositionUtilities.java

fix: UNPAYABLE should be considered for expiration date

---

src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/SendDebtPositionIONotificationActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/SendDebtPositionIONotificationActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/PaymentsReportingImplicitReceiptHandlerActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/PaymentsReportingImplicitReceiptHandlerActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/organization/BrokersRetrieverActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/organization/BrokersRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/organization/OrganizationBrokeredRetrieverActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/organization/OrganizationBrokeredRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/sendnotification/NotificationStatusActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/sendnotification/NotificationStatusActivityImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/SendDebtPositionIONotificationActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/PaymentsReportingImplicitReceiptHandlerActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/organization/BrokersRetrieverActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/organization/OrganizationBrokeredRetrieverActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/sendnotification/NotificationStatusActivityTest.java

…on, otherwise will be published by sync WF

fix: Activity methods renamed

---

src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/IONotificationDebtPositionActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/IONotificationDebtPositionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/dto/debtposition/GenericWfExecutionConfig.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/IONotificationDebtPositionActivityTest.java

fix: GenericWfExecutionConfig updated

---

src/main/java/it/gov/pagopa/payhub/activities/dto/debtposition/syncwfconfig/FineWfExecutionConfig.java

chore: Setting default FineWfExecutionConfig

---

src/main/java/it/gov/pagopa/payhub/activities/connector/ionotification/mapper/NotificationRequestMapper.java
src/test/java/it/gov/pagopa/payhub/activities/connector/ionotification/mapper/NotificationRequestMapperTest.java

fix: IO subject placeholder resolution

---

src/main/java/it/gov/pagopa/payhub/activities/aspect/NotRetryableActivityExceptionHandlerAspect.java

fix: Logging activity performance

---

src/main/java/it/gov/pagopa/payhub/activities/aspect/NotRetryableActivityExceptionHandlerAspect.java
src/test/java/it/gov/pagopa/payhub/activities/aspect/NotRetryableActivityExceptionHandlerAspectTest.java

fix: Activity Aspect should return returned value

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/SynchronizeIngestedDebtPositionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/workflowhub/WorkflowDebtPositionService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/workflowhub/WorkflowDebtPositionServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/workflowhub/client/WorkflowDebtPositionClient.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/SynchronizeIngestedDebtPositionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/workflowhub/WorkflowDebtPositionServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/workflowhub/client/WorkflowDebtPositionClientTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/workflowhub/config/WorkflowHubApisHolderTest.java

fix: Align to workflow-hub openapi

---

src/main/java/it/gov/pagopa/payhub/activities/activity/sendnotification/NotificationStatusActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/sendnotification/NotificationStatusActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/sendnotification/SendService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/sendnotification/SendServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/sendnotification/client/SendClient.java
src/test/java/it/gov/pagopa/payhub/activities/activity/sendnotification/NotificationStatusActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/sendnotification/SendServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/sendnotification/client/SendClientTest.java

fix: Align send-notification openApi

---

src/main/java/it/gov/pagopa/payhub/activities/activity/exportflow/ExportFileExpirationHandlerActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/BaseIngestionFlowFileActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/InstallmentIngestionFlowFileActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/treasury/TreasuryOpiIngestionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/IngestionFlowFileService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/IngestionFlowFileServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/client/IngestionFlowFileClient.java
src/main/java/it/gov/pagopa/payhub/activities/dto/export/ExportFlowFileVersions.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/email/IngestionFlowFileEmailTemplateResolverService.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/InstallmentIngestionFlowFileActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/treasury/TreasuryOpiIngestionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/IngestionFlowFileServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/client/IngestionFlowFileClientTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/config/ProcessExecutionsApisHolderTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/email/IngestionFlowFileEmailTemplateResolverServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/IngestionFlowFileFaker.java

fix: Align process-executions openApi

---

src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/IONotificationDebtPositionActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/IONotificationDebtPositionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/dto/debtposition/DebtPositionIoNotificationDTO.java
src/main/java/it/gov/pagopa/payhub/activities/service/debtposition/ionotification/IONotificationService.java
src/test/java/it/gov/pagopa/payhub/activities/activity/debtposition/ionotification/IONotificationDebtPositionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/debtposition/ionotification/IONotificationServiceTest.java

fix: Returning IO Messages details

---

src/main/java/it/gov/pagopa/payhub/activities/activity/classifications/TransferClassificationActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/debtposition/TransferService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/debtposition/TransferServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/debtposition/client/TransferClient.java
src/test/java/it/gov/pagopa/payhub/activities/activity/classifications/TransferClassificationActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/debtposition/TransferServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/debtposition/client/TransferClientTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/debtposition/config/DebtPositionApisHolderTest.java

fix: Storing IUF when notifying paymentsReporting on Transfer

---

src/main/java/it/gov/pagopa/payhub/activities/service/debtposition/ionotification/IONotificationService.java
src/test/java/it/gov/pagopa/payhub/activities/service/debtposition/ionotification/IONotificationServiceTest.java

fix: NullPointerException when no io-message has been sent

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/SynchronizeIngestedDebtPositionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/service/files/FileArchiverService.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/debtposition/DPInstallmentsWorkflowCompletionService.java

fix: Removing default on properties injected SPEL

---

src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/debtposition/InstallmentIngestionFlowFileResult.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/paymentnotification/PaymentNotificationIngestionFlowFileResult.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/paymentsreporting/PaymentsReportingIngestionFlowFileActivityResult.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/receipt/ReceiptPagopaIngestionFlowFileResult.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/treasury/TreasuryIufIngestionFlowFileResult.java

fix: IngestionFlowFileResult toString

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/SynchronizeIngestedDebtPositionActivityImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/SynchronizeIngestedDebtPositionActivityTest.java

fix: Synchronizing concurrently debt position after massive insert

---

src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/auth/AuthnService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/auth/AuthnServiceImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/auth/service/AuthAccessTokenRetriever.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/PaymentsReportingPagoPaService.java
src/main/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/PaymentsReportingPagoPaServiceImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaListRetrieverActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/paymentsreporting/OrganizationPaymentsReportingPagoPaRetrieverActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/auth/AuthnServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/auth/service/AuthAccessTokenRetrieverTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/pagopapayments/PaymentsReportingPagoPaServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileValidatorServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/paymentsreporting/PaymentsReportingMapperServiceTest.java

fix: PaymentsReporting fetch require organization auth token

---

src/main/java/it/gov/pagopa/payhub/activities/service/classifications/TransferClassificationStoreService.java
src/test/java/it/gov/pagopa/payhub/activities/service/classifications/TransferClassificationStoreServiceTest.java

fix: Classify transfer without ingestionFlowFileId

---

src/main/java/it/gov/pagopa/payhub/activities/connector/debtposition/client/InstallmentClient.java
src/test/java/it/gov/pagopa/payhub/activities/connector/debtposition/client/InstallmentClientTest.java

fix: Generating new debtpositions client from updated openApi

---

src/main/java/it/gov/pagopa/payhub/activities/aspect/NotRetryableActivityExceptionHandlerAspect.java

fix: Tracing workflow runId

---

src/main/java/it/gov/pagopa/payhub/activities/util/DebtPositionUtilities.java

fix: UNPAYABLE installment cannot EXPIRE

---

build.gradle.kts
src/main/java/it/gov/pagopa/payhub/activities/activity/classifications/IudClassificationActivityImpl.java
src/test/java/it/gov/pagopa/payhub/activities/activity/classifications/IudClassificationActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/InstallmentFaker.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/TransferFaker.java

fix: Aligned to debt-positions openApi

---

src/main/resources/config/application.yml

fix: Tmp folder read from system properties

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/treasury/TreasuryOpiIngestionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/connector/processexecutions/client/IngestionFlowFileClient.java
src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/IngestionFlowFileResult.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/debtposition/InstallmentProcessingService.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/TreasuryVersionBaseHandlerService.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/opi14/TreasuryVersionOpi14HandlerService.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/opi161/TreasuryVersionOpi161HandlerService.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/opi171/TreasuryVersionOpi171HandlerService.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/InstallmentIngestionFlowFileActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImplTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/treasury/TreasuryOpiIngestionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/client/IngestionFlowFileClientTest.java
src/test/java/it/gov/pagopa/payhub/activities/connector/processexecutions/config/ProcessExecutionsApisHolderTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/debtposition/InstallmentProcessingServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/TreasuryVersionBaseHandlerServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/opi14/TreasuryVersionOpi14HandlerServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/opi161/TreasuryVersionOpi161HandlerServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/ingestionflow/treasury/opi171/TreasuryVersionOpi171HandlerServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/util/faker/IngestionFlowFileFaker.java

fix: Updating IngestionFlowFile fileVersion field

---

src/main/java/it/gov/pagopa/payhub/activities/connector/organization/OrganizationApiServiceImpl.java

fix: P4ADEV-2869 fix annotation

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivityImpl.java
src/main/java/it/gov/pagopa/payhub/activities/config/FoldersPathsConfig.java
src/main/java/it/gov/pagopa/payhub/activities/mapper/ingestionflow/receipt/ReceiptMapper.java
src/main/java/it/gov/pagopa/payhub/activities/service/files/FileArchiverService.java
src/main/java/it/gov/pagopa/payhub/activities/service/files/XMLMarshallerService.java
src/main/java/it/gov/pagopa/payhub/activities/service/files/XMLUnmarshallerService.java
src/main/java/it/gov/pagopa/payhub/activities/service/ingestionflow/IngestionFlowFileRetrieverService.java
src/main/java/it/gov/pagopa/payhub/activities/service/receipt/RtFileHandlerService.java
src/main/resources/config/application.yml
src/test/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivityTest.java
src/test/java/it/gov/pagopa/payhub/activities/mapper/ingestionflow/receipt/ReceiptMapperTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/files/XMLMarshallerServiceTest.java
src/test/java/it/gov/pagopa/payhub/activities/service/receipt/RtFileHandlerServiceTest.java

fix: P4ADEV-2947 storing rtFilePath when arrive an RT

---

src/main/java/it/gov/pagopa/payhub/activities/mapper/exportflow/debtposition/InstallmentExportFlowFileDTOMapper.java
src/main/java/it/gov/pagopa/payhub/activities/mapper/exportflow/debtposition/ReceiptsArchivingExportFlowFileDTOMapper.java
src/test/java/it/gov/pagopa/payhub/activities/mapper/exportflow/debtposition/PaidInstallmentExportFlowFileDTOMapperTest.java
src/test/java/it/gov/pagopa/payhub/activities/mapper/exportflow/debtposition/ReceiptsArchivingExportFlowFileDTOMapperTest.java

fix: P4ADEV-2306 Setting RT xml on exports

---

src/main/resources/config/application.yml

fix: Fix rtFolder path

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/BaseIngestionFlowFileActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/IngestionFlowFileProcessorActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtposition/InstallmentIngestionFlowFileActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/debtpositiontype/DebtPositionTypeIngestionActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/organization/OrganizationIngestionActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentnotification/PaymentNotificationIngestionActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/receipt/ReceiptPagopaIngestionActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/treasury/TreasuryOpiIngestionActivity.java

fix: Fix IngetionFlowFilwProcessorActivity interfaces

---

src/main/java/it/gov/pagopa/payhub/activities/mapper/ingestionflow/receipt/ReceiptMapper.java
src/test/java/it/gov/pagopa/payhub/activities/mapper/ingestionflow/receipt/ReceiptMapperTest.java

feat: P4ADEV-2981 handle SourceFlowName

---

src/main/resources/config/application.yml

fix: Fixed default zip compression ratio

---

src/main/java/it/gov/pagopa/payhub/activities/aspect/NotRetryableActivityExceptionHandlerAspect.java

fix: Logging Activity attempt when > 1

---

src/main/java/it/gov/pagopa/payhub/activities/dto/ingestion/paymentnotification/PaymentNotificationIngestionFlowFileDTO.java

fix: Fixed PaymentNotificationCSV header column names

---

src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/BaseIngestionFlowFileActivity.java
src/main/java/it/gov/pagopa/payhub/activities/activity/ingestionflow/paymentsreporting/PaymentsReportingIngestionFlowFileActivityImpl.java

fix: Supporting payments reporting from pagoPa
